### ISSUE TITLE
npm package not found

### ISSUE THREAD

**Issue by cloudk1d** [FlafyDev/spicetify-creator#11]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Intel) 1.1.95.893.g6cf4d40c
- Spicetify version: 2.14.0
```

### 📝 Description

running ```npx create-spictify-app``` gives the following error.
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-spictify-app - Not found
npm ERR! 404
npm ERR! 404  'create-spictify-app@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by FlafyDev** [comment]
![image](https://user-images.githubusercontent.com/44374434/193739560-faf9e4b2-efac-47cc-9b4d-9abf2fd315d4.png)
Works for me just fine with `npm` version `8.19.1` and `node` version `18.9.1`.

It seems you have a typo in your command. Use `npx create-spicetify-app` instead.
