### ISSUE TITLE
Better Playlist Editor/Organizer

### ISSUE THREAD

**Issue by y0himba** [FlafyDev/spicetify-creator#12]
### 📝 Provide a description of the new feature

I have over 900 songs in my `Liked Songs` playlist.  The currently available online tools for organizing my music don't really allow me to sort by genre, then use that sort to add to a new playlist named for that genre. 

I am envisioning a nice GUI, the ability to sort by genre, checkboxes or just drag and select, then drag/drop to a new playlist. Maybe auto create a playlist from the genre selected.

I have a huge varied collection, rap/hip-hip/R&B/Slow jams. Bass heavy stuff to show off the system in my car, rock and blues for playing on my motorcycle, funk, pfunk, 50/60s, country, classical, etc.  All in my `Liked Songs` and all songs I have loved over my 57 years of life. Songs that mean a lot to me or set a certain mood for me etc.

We really need a much better way to edit, create and delete playlists, to organize our music lives in Spotify. 

Oh, and did I mention for desktop PC?  Windows and Linux?  I organize everything on PC then just plug my phone in and go.

I have asked for something like this for years. I have even contributed to folks who said they were making it, but never did.  

Thanks in advance to all you galaxy brains from a truck driving Navy Vet. 

### ➕ Additional Information

I think everything relevant is above. It can be a plugin, extension, or separate software, as long as it works. <3

**Comment by FlafyDev** [comment]
This does not relate to the development of `spicetify-creator` and thus should not be here.
You'll probably have better luck submitting a suggestion in the #suggestions channel of the [Spicetify Discord server](https://discord.gg/VnevqPp2Rr)
