### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by senolfndk** [FlafyDev/spicetify-creator#20]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30.1135.g02fef27a
- Spicetify version: v2.30.0 (2023-01-11)
```

### 📝 Description

mistake

### 📸 Screenshots

https://github.com/spicetify/spicetify-creator/assets/52818836/040af282-baf3-42fb-bd2c-42f763218a93

**Comment by AstudilloMarillo** [comment]
can confirm, same issue.

Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.30.0

_edit: quite quickly after, it worked again_
