### ISSUE TITLE
Error: Command failed: spicetify -c when running local build

### ISSUE THREAD

**Issue by jeroentvb** [FlafyDev/spicetify-creator#5]
I'm trying to set up a github action that automatically builds and pushes a new version to the `dist` branch on new pushes to `master`, but the action fails because spicetify-creator uses `spicetify -c` to get the path of the config dir. As far as I know that path isn't needed when running `npm run build-local`.

Currently the action fails, because the environment doesn't have spicetify installed. See the github action log [here](https://github.com/jeroentvb/spicetify-power-bar/runs/5309774031?check_suite_focus=true).

**Comment by FlafyDev** [comment]
Thanks. I just [pushed a patch](https://github.com/FlafyDev/spicetify-creator/commit/56df74ff95996260b08c4056384b018f56b05f94) to the repo to fix this. Do you need me to publish the new version to npm to test it? Or should I publish it after this issue is closed?

**Comment by jeroentvb** [comment]
I think that fixes it. A new version to npm would be great 👍
