### ISSUE TITLE
Is it possible to launch custom app with preset state?

### ISSUE THREAD

**Issue by theRealPadster** [FlafyDev/spicetify-creator#8]
### 📝 Provide a description of the new feature

I would like to pass a series of URIs to [my app](https://github.com/theRealPadster/spurdle), and launch it via the context menu. 

### ➕ Additional Information

The process for doing this is outlined [here](https://spicetify.app/docs/development/custom-apps#how-can-i-add-a-new-sub-page-or-path-to-my-custom-app), but I'm not sure how or if it's possible with Spicetify Creator, as I don't see the main render function itself.

**Comment by FlafyDev** [comment]
Solution in #9
